.\" Authors: Andre Masella
.TH pandaseq-checkid 1 "November 2012" "2.4" "USER COMMANDS"
.SH NAME 
pandaseq-checkid \- Illumina tag checker
.SH SYNOPSIS
.B pandaseq-checkid
.I 'sequenceid'
...
.SH DESCRIPTION
PANDASEQ is rather picky about the names of the paired-end Illumina reads. It attempts to validate that the have correct tags and flow cell information. Naturally, this causes a number of problems. This program shows the information as PANDAseq gathers it out of the FASTQ header.

If the output shows \fBhastag\fR to be false, then the \fB-B\fR flag should be passed to
.BR pandaseq (1).

.SH SEE ALSO
.BR pandaseq (1).
